import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface Step {
	id: string;
	name: string;
	baseUrl: string;
	associatedOptions: Record<string, string> | null;
}

const initialSteps: Array<Step> = [
	{
		id: 'lot',
		name: 'Lot',
		baseUrl: '/lot',
		associatedOptions: null,
	},
	{
		id: 'elevation',
		name: 'elevation',
		baseUrl: '/exterior',
		associatedOptions: { option: 'elevation' },
	},
	{
		id: 'landscaping',
		name: 'landscaping',
		baseUrl: '/exterior',
		associatedOptions: { option: 'landscaping' },
	},
	{
		id: 'exterior-color',
		name: 'exterior-color',
		baseUrl: '/exterior',
		associatedOptions: { option: 'exterior-color' },
	},
	{
		id: 'plan',
		name: 'plan',
		baseUrl: '/plan',
		associatedOptions: null,
	},
	// TODO these will be generated by the available cameras
	// TODO and rooms would be inferred, then each room will get it's own options by tag
	{
		id: 'kitchen:cabinet',
		name: 'Kitchen - Cabinets',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'kitchen', option: 'cabinet' },
	},
	{
		id: 'kitchen:flooring',
		name: 'Kitchen - Flooring',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'kitchen', option: 'flooring' },
	},
	{
		id: 'kitchen:counter',
		name: 'Kitchen - Counter',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'kitchen', option: 'counter' },
	},
	{
		id: 'kitchen:backsplash',
		name: 'Kithcen - Backsplash',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'kitchen', option: 'backsplash' },
	},
	{
		id: 'kitchen:fixtures',
		name: 'Kitchen - Fixtures',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'kitchen', option: 'fixtures' },
	},
	{
		id: 'kitchen:other',
		name: 'Kitchen - Other',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'kitchen', option: 'other' },
	},
	{
		id: 'master-bath:cabinets',
		name: 'Master Bath - Cabinets',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bath', option: 'cabinet' },
	},
	{
		id: 'master-bath:tile',
		name: 'Master Bath - Tile',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bath', option: 'tile' },
	},
	{
		id: 'master-bath:counter',
		name: 'Master Bath - Counter',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bath', option: 'counter' },
	},
	{
		id: 'master-bath:fixtures',
		name: 'Master Bath - Fixtures',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bath', option: 'fixtures' },
	},
	{
		id: 'master-bath:other',
		name: 'Master Bath - Other',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bath', option: 'other' },
	},
	{
		id: 'master-bed:flooring',
		name: 'Master Bed - Flooring',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bed', option: 'flooring' },
	},
	{
		id: 'master-bed:wall-color',
		name: 'Master Bed - Wall Color',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bed', option: 'wall-color' },
	},
	{
		id: 'master-bed:fixtures',
		name: 'Master Bed - Fixtures',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bed', option: 'fixtures' },
	},
	{
		id: 'master-bed:other',
		name: 'Master Bed - Other',
		baseUrl: '/interior-design',
		associatedOptions: { room: 'master-bed', option: 'other' },
	},
	// * End generated steps
	{
		id: 'review',
		name: 'Review',
		baseUrl: '/review',
		associatedOptions: null,
	},
];

interface StepState {
	isLoading: boolean;
	currentStepIndex: number;
	steps: Step[];
	lastUpdated: number;
}

export const useStepsStore = create<StepState>()((_set) => ({
	isLoading: false,
	currentStepIndex: 0,
	steps: initialSteps,
	lastUpdated: 0,
}));

export function setCurrentStepIndex(index: number) {
	useStepsStore.setState((state) => {
		return { ...state, currentStepIndex: index };
	});
}

export function gotoNextStep() {
	useStepsStore.setState((state) => {
		if (state.currentStepIndex === state.steps.length - 1) {
			console.log('Already at last step, not progressing');
			// * We're already at the last step, so don't do anything
			return state;
		}

		return { ...state, currentStepIndex: state.currentStepIndex + 1 };
	});
}

export function gotoPreviousStep() {
	useStepsStore.setState((state) => {
		if (state.currentStepIndex === 0) {
			console.log('Already at first step, not updating step');
			// * We're already at the first step, so don't do anything
			return state;
		}

		return { ...state, currentStepIndex: state.currentStepIndex - 1 };
	});
}

// * This is a best guess based on the current URL and the associated options
// * for each step. It's not perfect, but it's a good start.
// * It basically compares and sees how many things match. The step with the most
// * matching items to the URL wins!
export function getStepIndexByUrl(
	baseUrl: string,
	searchParams?: Record<string, string>
) {
	const bestStepMatch = initialSteps.reduce(
		(acc, step, index) => {
			let matchingScore = 0;

			if (step.baseUrl === baseUrl) {
				matchingScore++;
			}

			if (step.associatedOptions && searchParams) {
				for (const [key, value] of Object.entries(searchParams)) {
					if (step.associatedOptions[key] === value) {
						matchingScore++;
					}
				}
			}

			if (matchingScore > acc.matchingScore) {
				return { matchingScore, ...step, index };
			} else return acc;
		},
		{ matchingScore: 0, index: 0 }
	);

	// console.log('best step match', { bestStepMatch });
	return bestStepMatch?.index || 0;
}
